version: '2.3'

services:

  cnn_counting:
    image: cnn_counting
    container_name: cnn_counting
    working_dir: /cnn_counting
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/cnn_counting
      
    runtime: nvidia
    command: tail /dev/null -f
